// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.1
// source: yys.proto

package yys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type SetYysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ordersn string `protobuf:"bytes,1,opt,name=ordersn,proto3" json:"ordersn,omitempty"`
}

func (x *SetYysRequest) Reset() {
	*x = SetYysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetYysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetYysRequest) ProtoMessage() {}

func (x *SetYysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetYysRequest.ProtoReflect.Descriptor instead.
func (*SetYysRequest) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{1}
}

func (x *SetYysRequest) GetOrdersn() string {
	if x != nil {
		return x.Ordersn
	}
	return ""
}

type CalculateInventoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ordersn          string `protobuf:"bytes,1,opt,name=ordersn,proto3" json:"ordersn,omitempty"`
	DefaultCritRate  string `protobuf:"bytes,2,opt,name=default_crit_rate,json=defaultCritRate,proto3" json:"default_crit_rate,omitempty"`
	DefaultCritPower string `protobuf:"bytes,3,opt,name=default_crit_power,json=defaultCritPower,proto3" json:"default_crit_power,omitempty"`
}

func (x *CalculateInventoryReq) Reset() {
	*x = CalculateInventoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateInventoryReq) ProtoMessage() {}

func (x *CalculateInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateInventoryReq.ProtoReflect.Descriptor instead.
func (*CalculateInventoryReq) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateInventoryReq) GetOrdersn() string {
	if x != nil {
		return x.Ordersn
	}
	return ""
}

func (x *CalculateInventoryReq) GetDefaultCritRate() string {
	if x != nil {
		return x.DefaultCritRate
	}
	return ""
}

func (x *CalculateInventoryReq) GetDefaultCritPower() string {
	if x != nil {
		return x.DefaultCritPower
	}
	return ""
}

type CalculateInventoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rst []*RepeatedInventory `protobuf:"bytes,1,rep,name=Rst,proto3" json:"Rst,omitempty"`
}

func (x *CalculateInventoryResp) Reset() {
	*x = CalculateInventoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateInventoryResp) ProtoMessage() {}

func (x *CalculateInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateInventoryResp.ProtoReflect.Descriptor instead.
func (*CalculateInventoryResp) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateInventoryResp) GetRst() []*RepeatedInventory {
	if x != nil {
		return x.Rst
	}
	return nil
}

type RepeatedInventory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rst []*Inventory `protobuf:"bytes,1,rep,name=Rst,proto3" json:"Rst,omitempty"`
}

func (x *RepeatedInventory) Reset() {
	*x = RepeatedInventory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedInventory) ProtoMessage() {}

func (x *RepeatedInventory) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedInventory.ProtoReflect.Descriptor instead.
func (*RepeatedInventory) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{4}
}

func (x *RepeatedInventory) GetRst() []*Inventory {
	if x != nil {
		return x.Rst
	}
	return nil
}

type Inventory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pos             int32         `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Attr            string        `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	InventoryId     string        `protobuf:"bytes,4,opt,name=inventoryId,proto3" json:"inventoryId,omitempty"`
	SingleAttrName  string        `protobuf:"bytes,5,opt,name=singleAttrName,proto3" json:"singleAttrName,omitempty"`
	SingleAttrValue float64       `protobuf:"fixed64,6,opt,name=singleAttrValue,proto3" json:"singleAttrValue,omitempty"`
	SecondAttr      []*SecondAttr `protobuf:"bytes,7,rep,name=secondAttr,proto3" json:"secondAttr,omitempty"`
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{5}
}

func (x *Inventory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Inventory) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *Inventory) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *Inventory) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *Inventory) GetSingleAttrName() string {
	if x != nil {
		return x.SingleAttrName
	}
	return ""
}

func (x *Inventory) GetSingleAttrValue() float64 {
	if x != nil {
		return x.SingleAttrValue
	}
	return 0
}

func (x *Inventory) GetSecondAttr() []*SecondAttr {
	if x != nil {
		return x.SecondAttr
	}
	return nil
}

type SecondAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SecondAttr) Reset() {
	*x = SecondAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yys_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecondAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondAttr) ProtoMessage() {}

func (x *SecondAttr) ProtoReflect() protoreflect.Message {
	mi := &file_yys_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondAttr.ProtoReflect.Descriptor instead.
func (*SecondAttr) Descriptor() ([]byte, []int) {
	return file_yys_proto_rawDescGZIP(), []int{6}
}

func (x *SecondAttr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecondAttr) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_yys_proto protoreflect.FileDescriptor

var file_yys_proto_rawDesc = []byte{
	0x0a, 0x09, 0x79, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x79, 0x73,
	0x22, 0x22, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x59, 0x79, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x6e, 0x22,
	0x8b, 0x01, 0x0a, 0x15, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x63,
	0x72, 0x69, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x69, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x5f,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x69, 0x74, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x42, 0x0a,
	0x16, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x03, 0x52, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x79, 0x79, 0x73, 0x2e, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x03, 0x52, 0x73,
	0x74, 0x22, 0x35, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x52, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x79, 0x79, 0x73, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x03, 0x52, 0x73, 0x74, 0x22, 0xea, 0x01, 0x0a, 0x09, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x74, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x74,
	0x74, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79, 0x79, 0x73, 0x2e, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x74, 0x74, 0x72, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x41, 0x74, 0x74, 0x72, 0x22, 0x36, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41,
	0x74, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x85, 0x01,
	0x0a, 0x03, 0x59, 0x79, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x65, 0x74, 0x59, 0x79, 0x73, 0x12,
	0x12, 0x2e, 0x79, 0x79, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x59, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x79, 0x79, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x79,
	0x79, 0x73, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x79, 0x79, 0x73, 0x2e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x79, 0x79, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yys_proto_rawDescOnce sync.Once
	file_yys_proto_rawDescData = file_yys_proto_rawDesc
)

func file_yys_proto_rawDescGZIP() []byte {
	file_yys_proto_rawDescOnce.Do(func() {
		file_yys_proto_rawDescData = protoimpl.X.CompressGZIP(file_yys_proto_rawDescData)
	})
	return file_yys_proto_rawDescData
}

var file_yys_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_yys_proto_goTypes = []interface{}{
	(*BaseResponse)(nil),           // 0: yys.BaseResponse
	(*SetYysRequest)(nil),          // 1: yys.SetYysRequest
	(*CalculateInventoryReq)(nil),  // 2: yys.CalculateInventoryReq
	(*CalculateInventoryResp)(nil), // 3: yys.CalculateInventoryResp
	(*RepeatedInventory)(nil),      // 4: yys.repeatedInventory
	(*Inventory)(nil),              // 5: yys.inventory
	(*SecondAttr)(nil),             // 6: yys.secondAttr
}
var file_yys_proto_depIdxs = []int32{
	4, // 0: yys.CalculateInventoryResp.Rst:type_name -> yys.repeatedInventory
	5, // 1: yys.repeatedInventory.Rst:type_name -> yys.inventory
	6, // 2: yys.inventory.secondAttr:type_name -> yys.secondAttr
	1, // 3: yys.Yys.setYys:input_type -> yys.SetYysRequest
	2, // 4: yys.Yys.calculateInventory:input_type -> yys.CalculateInventoryReq
	0, // 5: yys.Yys.setYys:output_type -> yys.BaseResponse
	3, // 6: yys.Yys.calculateInventory:output_type -> yys.CalculateInventoryResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yys_proto_init() }
func file_yys_proto_init() {
	if File_yys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetYysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateInventoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yys_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateInventoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yys_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedInventory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yys_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inventory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yys_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecondAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yys_proto_goTypes,
		DependencyIndexes: file_yys_proto_depIdxs,
		MessageInfos:      file_yys_proto_msgTypes,
	}.Build()
	File_yys_proto = out.File
	file_yys_proto_rawDesc = nil
	file_yys_proto_goTypes = nil
	file_yys_proto_depIdxs = nil
}
