// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	Id string `path:"id"`
}

type UserReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type JwtReply struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}
