// Code generated by goctl. DO NOT EDIT.
package types

type BaseReq struct {
	Code int `json:"code"`
}

type UserReq struct {
	Id int `path:"id"`
}

type UserReply struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type JwtReply struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type YysReq struct {
	Ordersn string `json:"ordersn"`
}

type CalculateInventoryReq struct {
	Ordersn          string `json:"ordersn"`
	DefaultCritRate  string `json:"default_crit_rate"`
	DefaultCritPower string `json:"default_crit_power"`
}

type CalculateInventoryResp struct {
	Rst []InventoryBig `json:"rst"`
}

type InventoryBig struct {
	Rst []Inventory `json:"rst"`
}

type Inventory struct {
	Name            string       `json:"name"`
	Pos             int          `json:"pos"`
	Attr            string       `json:"attr"`
	InventoryId     string       `json:"inventory_id"`
	SecondAttr      []SecondAttr `json:"second_attr"`
	SingleAttrValue float64      `json:"single_attr_value"`
	SingleAttrName  string       `json:"single_attr_name"`
}

type SecondAttr struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}
